### ISSUE TITLE
Tony DJ & Spotify Music Lover's

### ISSUE THREAD

**Issue by TonyDJ59** [BalajiDhanaraj/Data-Structures-Algorithms#9]
Spotify has become the particular trending topic on social media. Music is loved, because it plays an essential role in the experience of people in the world. Listening to music or any song arouses different emotions in each of us, satisfies our listening with any genre you hear in any place and time. But whatever technology DJs use to develop a Playlist to play music, the reasons for listening to it are universal.

**Comment by TonyDJ59** [comment]
[SUPER LATINA!](https://open.spotify.com/playlist/7012fYHDW65zfw6OyRqVCi?si=b01218ded1ea4845)

**Comment by BalajiDhanaraj** [comment]
what your try to say?
